-------------------------<SQL01_SELECT(BASIC)>-------------------------
--1. 
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;


--2
SELECT DEPARTMENT_NAME ||'의 정원은 ' || CAPACITY|| '명 입니다' "학과별 정원"
FROM TB_DEPARTMENT;


--3
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 001 
AND SUBSTR(STUDENT_SSN, 8, 1) = 2 
AND ABSENCE_YN = 'Y';


--4
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO = 'A513079'
OR STUDENT_NO = 'A513090'
OR STUDENT_NO = 'A513091'
OR STUDENT_NO = 'A513110'
OR STUDENT_NO = 'A513119'
ORDER BY STUDENT_NAME DESC;


--5
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN '20' AND '30';


--6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


--7 
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;


--8
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO != NULL;


--9
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;


--10
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002'
AND STUDENT_ADDRESS LIKE '전주%'
AND ABSENCE_YN ='N';

-------------------------<SQL02_SELECT(FUNCTION)>------------------------------
--1
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_DATE(ENTRANCE_DATE, 'RR-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;


--2 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';



--3***********************************
SELECT PROFESSOR_NAME 교수이름, EXTRACT(PROFESSOR_SSN, 'RR-MM-DD') 나이
FROM TB_PROFESSOR
WHERE 
ORDER BY ;


--4
SELECT SUBSTR(PROFESSOR_NAME, 2, 3) 이름
FROM TB_PROFESSOR ;


--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) !=19 ;


--6 **************************
SELECT  FROM DUAL;
SELECT TO_DATE(20201225, 'YYYYMMDD DAY') FROM DUAL; 



--7
SELECT TO_DATE('99/10/11', 'YY/MM/DD') FROM DUAL; -- 2099-10-11 00:00:00.000
SELECT TO_DATE('49/10/11', 'YY/MM/DD') FROM DUAL; -- 2049-10-11 00:00:00.000
SELECT TO_DATE('99/10/11', 'RR/MM/DD') FROM DUAL; -- 1999-10-11 00:00:00.000
SELECT TO_DATE('49/10/11', 'RR/MM/DD') FROM DUAL; -- 2049-10-11 00:00:00.000

--8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A';

--9
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE;

--10
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11 ************************************
SELECT COACH_PROFESSOR_NO, COUNT(*)
FROM TB_STUDENT
GROUP BY COACH_PROFESSOR_NO
ORDER BY COACH_PROFESSOR_NO
WHERE ;

WHERE COACH_PROFESSOR_NO

--12
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT;

SELECT 
--13
--14
--15



--------------------------<SQL03_SELECT(OPTION)>-------------------------
-- 1. 
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT 
ORDER BY"학생 이름";



-- 2.
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y';



-- 3. 
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '강원도%'
OR STUDENT_ADDRESS LIKE'경기도%')
AND STUDENT_NO NOT LIKE 'A%'
ORDER BY STUDENT_NAME;


-- 4. 
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;


-- 5.
SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE TERM_NO = '200402' 
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO;



-- 6. ********************** 답안 확인****************예시와 RESULT SET 달라
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME;


-- 7. 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);

-------------------------------------------여기까진 맞음
-- 8.----------------------------------다시-  답안
SELECT DISTINCT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO);


-- 9. ----------------------------------다시-  답안
SELECT CLASS_NAME, PROFESSOR_NAME, CATEGORY
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';


-- 10.
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름", ROUND(AVG(POINT), 1) "전체 평점"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;


-- 11. ----------------------------------다시-  답안
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';


-- 12. ---------- 문제 오류 TERM_NAME -> TERM_NO
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (DEPARTMENT_NO)
WHERE (TERM_NO LIKE '2007%') AND CLASS_NAME = '인간관계론'
ORDER BY STUDENT_NAME ;


SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT;










































